# Generated by Django 4.2.3 on 2023-07-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(verbose_name='Enrollment Date')),
                ('first_name', models.CharField(max_length=36, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('family_size', models.PositiveSmallIntegerField(default=1, verbose_name='Family Size')),
                ('over64', models.PositiveSmallIntegerField(default=0, verbose_name='Over 64')),
                ('under19', models.PositiveSmallIntegerField(default=0, verbose_name='Under 19')),
                ('addr_line_1', models.CharField(max_length=60, verbose_name='Address 1')),
                ('addr_line_2', models.CharField(blank=True, max_length=60, verbose_name='Address 2')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='CO', verbose_name='State')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zipcode')),
                ('jeffco_resident', models.BooleanField(default=True, verbose_name='Jeffco Resident')),
                ('data_review_date', models.DateTimeField(verbose_name='Data Review Date')),
                ('ethnicity', models.CharField(choices=[('D', 'Will not answer'), ('W', 'White'), ('H', 'Hispanic'), ('A', 'Asian'), ('B', 'Black'), ('N', 'Native')], default='D', verbose_name='Ethnicity')),
                ('validated', models.BooleanField(default=False, verbose_name='Validated')),
                ('validated_date', models.DateTimeField(verbose_name='Validated Date')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
                ('comments', models.CharField(blank=True, max_length=320, verbose_name='Comments')),
            ],
        ),
    ]
