# Generated by Django 4.2.3 on 2023-09-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Banned'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=False, verbose_name='Visit Date')),
                ('line_number', models.PositiveSmallIntegerField(default=False, verbose_name='Line Number')),
                ('commodities_box', models.PositiveSmallIntegerField(default=False, verbose_name='Commodities Box')),
                ('commodities_box_num', models.PositiveSmallIntegerField(default=False, verbose_name='Commodities Box Num')),
                ('commodities_line_num', models.PositiveSmallIntegerField(default=False, verbose_name='Commodities Line Num')),
                ('commodities_box_pack', models.PositiveSmallIntegerField(default=False, verbose_name='Commodities Box Pack')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
